name: context
on:
  - push
jobs:
  hello-world:
    if: github.repository == 'Swathi/Github-Examples'
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hello world"
  goodbye-moon:
    runs-on: ubuntu-latest
    steps:
      - name: good bye
        run: echo "Good Bye Moon"