name: example-workflow
on:
  - push
jobs:
  hello-world:
    if: github.repository == 'Swathi-K-tech/Github-Examples'
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hello world"
  goodbye-moon:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hello world"